### Information
## Sounds
# To know what sound to use, look at the Sound Events found here: https://minecraft.wiki/w/Sounds.json#Sound_events

## Generic
safe_fall_distance: 6.0 # Applies to anyone with the massivecombat.safer_fall permission.
disable_invulnerability_frames: false # Applies to all entities in the world.

## Movement
# Double Jump
# Only applies to players with the massivecombat.ability.starter.double_jump permission node.
double_jump_multiple: 0.5
double_jump_setY: 0.5
double_jump_sound: "entity.breeze.idle_air"
double_jump_use_cooldown: false
double_jump_cooldown: 100 # Value in ticks. Ignored if double_jump_use_cooldown is false.

# Wall Jump
# Only applies to players with the massivecombat.ability.starter.wall_jump permission node.
wall_jump_multiple: 0.35
wall_jump_setY: 0.55
wall_jump_sound: "entity.breeze.jump"
wall_jump_use_cooldown: false
wall_jump_cooldown: 100 # Value in ticks. Ignored if wall_jump_use_cooldown is false.
wall_jump_num_of_jumps: 2 # How many times you can wall jump in a row
wall_jump_min_distance: 3 # The minimum distance you need to move on the x and z axis to wall jump again.

# Sliding
# Only applies to players with the massivecombat.ability.starter.slide permission node.
slide_multiple: 0.6
slide_sound: "item.brush.brushing.gravel"
slide_use_cooldown: false
slide_cooldown: 100 # Value in ticks. Ignored if slide_use_cooldown is false.
slide_craw_duration: 10 # How many ticks you should be in crawl mode after slide is activated.

## Combat
# Deflection
deflection_use_hold_frequency: 10 # The delay of ticks between checking if the player is still holding right-click.
deflection_whitelist_tags: # the item in your offhand needs one of these tags to enable deflection.
  - "deflecting"
deflection_minimum_angle: 8.0 # The angle in degrees that you have to match a projectile to deflect it.
deflection_sound: "entity.breeze.deflect"
deflection_use_cooldown: false
deflection_cooldown: 100 # Value in ticks. Ignored if double_jump_use_cooldown is false.

# Backstab
backstab_damage: 3.0 # Bonus damage to be applied when attacking an entity facing away from you.
backstab_angle: 30.0 # How many degrees of leeway you have compared the entity in order to count as being "behind"
backstab_sound: "item.wolf_armor.damage"

# Health Effects
# Only applies to players with the massivecombat.health_effects permission node.
slowness_ticks_per_block_fallen: 200 # Gives 10 seconds of slowness for every block of fall damage.
low_health_effects:
  1:
    adds:
      WEAKNESS: 0
      MINING_FATIGUE: 0
      NAUSEA: 0
      BLINDNESS: 0
  2:
    copy: 1
  3:
    copy: 1
  4:
    copy: 1
  5:
    adds:
      WEAKNESS: 0
      MINING_FATIGUE: 0
      NAUSEA: 0
      DARKNESS: 0
  6:
    copy: 5
  7:
    adds:
      WEAKNESS: 0
      MINING_FATIGUE: 0
      NAUSEA: 0
  8:
    copy: 7
  9:
    adds:
      WEAKNESS: 0
      MINING_FATIGUE: 0
  10:
    copy: 9
  11:
    copy: 9
  12:
    adds:
      WEAKNESS: 0
  13:
    copy: 12
  14:
    copy: 12
LHE_duration: 200 # Duration of low health effects in ticks.

## Items
# Must be added through other means, my plugin only deals with the use of the item.
# Healing
healing_items:
  bandage:
    tag: "bandage" # The tag to look for in the item to count as a "bandage".
    heal_amount: 5 # Health points to heal, 1 being half a heart.
    instant: false # Whether the item should be used instantly on right-click.
    use_time: 100 # How long you need to hold right-click until the item is used, in ticks.
    used_effects: # Effects to gain after item is used.
      REGENERATION:
        level: 0 # Level of the effect; 0 is actually level 1.
        duration: 200 # Duration in ticks.
    remove_effects: # Effects to remove after item is used.
      - BLEEDING # Removes the custom "bleeding" effect.
    during_effects: # Effects to gain while holding right-click with the item.
      SLOWNESS: 0 # name: level (duration is constant as long as you hold right-click)
  splinters:
    tag: "splinters"
    instant: false
    use_time: 100
    remove_effects:
      - SLOWNESS
  